export const doctorType = [
  { value: "Allergist", label: "Allergist" },
  { value: "Anesthesiologist", label: "Anesthesiologist" },
  {
    value: "Cardiac Electrophysiologist",
    label: "Cardiac Electrophysiologist",
  },
  { value: "Cardiothoracic Surgeon", label: "Cardiothoracic Surgeon" },
  { value: "Colorectal Surgeon", label: "Colorectal Surgeon" },
  {
    value: "Critical Care Medicine Specialist",
    label: "Critical Care Medicine Specialist",
  },
  { value: "Dermatologist", label: "Dermatologist" },
  {
    value: "Emergency Medicine Physician",
    label: "Emergency Medicine Physician",
  },
  { value: "Endocrinologist", label: "Endocrinologist" },
  { value: "Family Physician", label: "Family Physician" },
  { value: "Gastroenterologist", label: "Gastroenterologist" },
  { value: "General Practitioner", label: "General Practitioner" },
  { value: "Geriatrician", label: "Geriatrician" },
  { value: "Gynecologist", label: "Gynecologist" },
  { value: "Hematologist", label: "Hematologist" },
  {
    value: "Infectious Disease Specialist",
    label: "Infectious Disease Specialist",
  },
  { value: "Internist", label: "Internist" },
  { value: "Neurologist", label: "Neurologist" },
  { value: "Nephrologist", label: "Nephrologist" },
  { value: "Oncologist", label: "Oncologist" },
  { value: "Ophthalmologist", label: "Ophthalmologist" },
  { value: "Orthopedic Surgeon", label: "Orthopedic Surgeon" },
  {
    value: "Otolaryngologist",
    label: "Otolaryngologist (Ear, Nose, and Throat)",
  },
  { value: "Pathologist", label: "Pathologist" },
  { value: "Pediatrician", label: "Pediatrician" },
  { value: "Physiatrist", label: "Physiatrist" },
  { value: "Plastic Surgeon", label: "Plastic Surgeon" },
  { value: "Podiatrist", label: "Podiatrist" },
  { value: "Psychiatrist", label: "Psychiatrist" },
  { value: "Pulmonologist", label: "Pulmonologist" },
  { value: "Radiologist", label: "Radiologist" },
  { value: "Rheumatologist", label: "Rheumatologist" },
  { value: "Sports Medicine Physician", label: "Sports Medicine Physician" },
  { value: "Surgeon", label: "Surgeon" },
  { value: "Thoracic Surgeon", label: "Thoracic Surgeon" },
  { value: "Urogynecologist", label: "Urogynecologist" },
  { value: "Urologist", label: "Urologist" },
  { value: "Vascular Surgeon", label: "Vascular Surgeon" },
];
